version: '3'
 
services:
  app:
    image: ${DOCKER_IMAGE_COMPOSE}
    container_name: ${DOCKER_CONTAINER_NAME}
    expose:
      - "5000"
    environment:
      APP_DB_SECRET: /app/db-secret
      APP_DB_DEV_SECRET: /app/db-secret-dev
    volumes:
      - secrets/db-secret-prod:/app/db-secret
      - secrets/db-secret-dev:/app/db-secret-dev
