language: python

dist: trusty

services:
  - docker

python:
  - "3.7"

if: tags IS blank

matrix:
  fast_finish: true


before_install:
  - configure_jfrog_client

script:
  - make docker-build

after_success:
  - reports-publisher

after_failure:
  - reports-publisher

deploy:
  - provider: script
    script: make docker-publish
    on:
      all_branches: true