- defaultTab: nodes
  description: |-
        sudo docker run -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -v /home/bnbiuser/secrets/aws-secret:/app/aws-secret \
                        -e APP_AWS_SECRET=/app/aws-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/liquidity-content:feat_liquidity-content
  executionEnabled: true
  group: DOCKER/LIQUIDITY
  loglevel: DEBUG
  name: Liquidity - Ads contents to s3
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notifyAvgDurationThreshold: null
  scheduleEnabled: false
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/liquidity-content:feat_liquidity-content
        sudo docker run -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -v /home/bnbiuser/secrets/aws-secret:/app/aws-secret \
                        -e APP_AWS_SECRET=/app/aws-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/liquidity-content:feat_liquidity-content
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
  