FROM python:3.9.18-slim

COPY ./app /app
WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc build-essential \
    && apt-get install -y --no-install-recommends gawk \
    && apt-get install -y --no-install-recommends grep \
    && apt-get install -y libpq-dev \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --upgrade pip setuptools \
    && pip install -r requirements.txt \
    && apt-get purge -y --auto-remove gcc build-essential

ENTRYPOINT [ "bash", "/app/scripts/entrypoint.sh" ]