- defaultTab: nodes
  description: |-
        This pipeline make queries related to products and packs to Blocket DB and leave data in datawarehouse
        sudo docker run --net=host --rm -v /home/bnbiuser/secrets/blocket_db:/app/blocket-secret \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_BLOCKET_SECRET=/app/blocket-secret \
                        -e APP_DW_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/etl-job-blocket:feat_etl_job_blocket_crontab
  executionEnabled: true
  group: CONTENT
  loglevel: DEBUG
  name: Ingestion - ETL Data Ingestion Blocket - Packs-Products
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notifyAvgDurationThreshold: null
  schedule:
    month: '*'
    time:
      hour: '00'
      minute: '10'
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/etl-job-blocket:feat_etl_job_blocket_crontab
        sudo docker run --net=host --rm -v /home/bnbiuser/secrets/blocket_db:/app/blocket-secret \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_BLOCKET_SECRET=/app/blocket-secret \
                        -e APP_DW_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/etl-job-blocket:feat_etl_job_blocket_crontab
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
