- defaultTab: nodes
  description: |-
        Retrieves data to be used in tableau online for inserting fee \
        sudo docker run --rm -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/tableau-kpi-fraude:latest
  executionEnabled: true
  group: DOCKER/CONTENT
  loglevel: DEBUG
  name: CONTENT - Tableau Kpi Fraude
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notification:
    onfailure:
      email:
        recipients: gp_data_analytics@yapo.cl
        subject: ${job.execid} ${execution.status} ${job.name} - Fallo definitivo
      plugin:
        configuration:
          slack_channel: ''
          webhook_base_url: https://hooks.slack.com/services
          webhook_token: T02U92SBN/B024F0M8EF5/6jLC6tWl4QNrYFpnyoLqqQZI
        type: SlackNotification
  notifyAvgDurationThreshold: null
  schedule:
    month: '*'
    time:
      hour: '9'
      minute: '0'
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/tableau-kpi-fraude:latest
        sudo docker run --rm -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/tableau-kpi-fraude:latest
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
