- defaultTab: nodes
  description: |-
        sudo docker pull registry.gitlab.com/yapo_team/legacy/data-analytics/data-content:${IMAGE_TAG}

        sudo docker run -v /home/bnbiuser/secrets/pulse_auth:/app/pulse-secret \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -v /home/bnbiuser/secrets/blocket_db:/app/blocket-secret \
                        -e APP_PULSE_SECRET=/app/pulse-secret \
                        -e APP_DB_SECRET=/app/blocket-secret \
                        -e APP_DW_SECRET=/app/db-secret \
                        registry.gitlab.com/yapo_team/legacy/data-analytics/data-content:${IMAGE_TAG}
  executionEnabled: true
  group: GLOBAL-METRIC
  loglevel: DEBUG
  name:  Peak - Content-Metrics
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notification:
    onfailure:
      email:
        recipients: gp_data_analytics@yapo.cl
        subject: ${job.execid} ${execution.status} ${job.name} - Fallo definitivo
      plugin:
        configuration:
          slack_channel: ''
          webhook_base_url: https://hooks.slack.com/services
          webhook_token: T02U92SBN/B024F0M8EF5/6jLC6tWl4QNrYFpnyoLqqQZI
        type: SlackNotification
  notifyAvgDurationThreshold: null
  scheduleEnabled: true
  schedule:
    month: '*'
    time:
      hour: '09'
      minute: '0'
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  retry:
    retry: 3
    delay: 20m
  sequence:
    commands:
    - script: |-
        sudo docker pull registry.gitlab.com/yapo_team/legacy/data-analytics/data-content:${IMAGE_TAG}

        sudo docker run -v /home/bnbiuser/secrets/pulse_auth:/app/pulse-secret \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -v /home/bnbiuser/secrets/blocket_db:/app/blocket-secret \
                        -e APP_PULSE_SECRET=/app/pulse-secret \
                        -e APP_DB_SECRET=/app/blocket-secret \
                        -e APP_DW_SECRET=/app/db-secret \
                        registry.gitlab.com/yapo_team/legacy/data-analytics/data-content:${IMAGE_TAG}
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
