- defaultTab: nodes
  description: |-
        Ejecutando pruebas de funcionamiento
        sudo docker run --net=host --rm -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/retention-seller-pack:latest \
                        -email_from="noreply@yapo.cl" \
                        -email_to="email to send data" \
                        -email_to="email2 to send data" \
                        -date_to="YYYY-MM-DD" \
                        -date_from="YYYY-MM-DD" 
  executionEnabled: true
  group: CONTENT
  loglevel: DEBUG
  name: Content - Retention sellers packs
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notifyAvgDurationThreshold: null
  scheduleEnabled: false
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/retention-seller-pack:latest
        sudo docker run --net=host --rm -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/retention-seller-pack:latest \
                        -email_from="noreply@yapo.cl" \
                        -email_to="ricardo.alvarez@adevinta.com" \
                        -email_to="ana.mora@adevinta.com" \
                        -email_to="mauricio.wittenberg@adevinta.com"
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
