
FROM containers.mpi-internal.com/yapo/data-spark-base

COPY . /app
WORKDIR /app

ENV APP_HOME /app
ENV CONFIGURATION_FILE ${APP_HOME}/resources/conf.properties

RUN python3 -m pip install --no-cache-dir -r ${APP_HOME}/requirements.txt
