# One .gitlab-ci.yml file for each project must be present.
# In order to run the docker-pipeline-template, a Dockerfile symlink must be placed
# into data-content/seller-return-over-current/Dockerfile (`ln -s ./app/dockerfile ./Dockerfile`).

"docker-push-hash:seller-return-over-current":
  extends: .docker-push-hash
  only:
    variables:
      - '$CI_COMMIT_BRANCH == "master" && ($CI_COMMIT_MESSAGE =~ /seller-return-over-current/ || $SUBFOLDER == "seller-return-over-current")'
  variables:
    CI_COMMIT_SHORT_SHA: "${CI_COMMIT_SHORT_SHA}_seller-return-over-current"
    IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}"
  before_script:
    - cd ./seller-return-over-current/
    - sleep 5
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

"deploy-rundeck:seller-return-over-current":
  extends: .deploy-rundeck
  dependencies:
    - docker-push-hash:seller-return-over-current
  when: manual
  only:
    variables:
      - '$CI_COMMIT_BRANCH == "master" && ($CI_COMMIT_MESSAGE =~ /seller-return-over-current/ || $SUBFOLDER == "seller-return-over-current")'
  variables:
    IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}_seller-return-over-current"
    RUNDECK_MANIFEST: "deploy/rundeck.yaml"
    RUNDECK_PROJECT: "data_jobs"
  before_script:
    - apk add --no-cache curl gettext
    - cd ./seller-return-over-current/
