- defaultTab: nodes
  description: |-
        This pipeline get statistics about the ads reviews and times that take, and send info in excel format for email.
        sudo docker run --net=host --rm -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/send_email_besedo:latest
                        -email_from="noreply@yapo.cl -- if put this options replace default email from" \
                        -email_to="email 1 to send data -- if put this options replace default emails to" \
                        -email_to="email 2 to send data" \
                        -email_to="email n to send data" \
                        -date_to="YYYY-MM-DD" \
                        -date_from="YYYY-MM-DD"\
                        
  executionEnabled: true
  group: CONTENT
  loglevel: DEBUG
  name: Review - Send email besedo
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notification:
    onfailure:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name}
    onstart:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name}
    onsuccess:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name}
  notifyAvgDurationThreshold: null
  schedule:
    month: '*'
    time:
      hour: '04'
      minute: '0'
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/send_email_besedo:latest
        sudo docker run --net=host --rm -v /home/bnbiuser/secrets/blocket_db:/app/db-secret \
                        -e APP_DB_SECRET=/app/db-secret\
                        containers.mpi-internal.com/yapo/send_email_besedo:latest\
                        -email_from="noreply@yapo.cl"\
                        -email_to="data_team@adevinta.com"
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
