# One .gitlab-ci.yml file for each project must be present.
# In order to run the docker-pipeline-template, a Dockerfile symlink must be placed
# into data-content/peak-content-sac/Dockerfile (`ln -s ./app/dockerfile ./Dockerfile`).

# TODO: build and push a Docker image to the GitLab package registry.

default:
  before_script:
    # make a symlink named data-content/Dockerfile pointing to data-content/peak-content-sac/Dockerfile
    - ln -s Dockerfile ./peak-content-sac/Dockerfile
    - cd ./peak-content-sac/

include:
  - project: 'yapo_team/yotf/sre-team/sre-services/ci-templates/docker-pipeline-template'
    ref: master
    file: 'gitlab-ci.yml'


stages:
  - build-docker

docker-push-release:
  extends: .docker-push-release
  only:
    - master
  variables:
    IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}+peak-content-sac"