# One .gitlab-ci.yml file for each project must be present.
# In order to run the docker-pipeline-template, a Dockerfile symlink must be placed
# into data-content/peak-content-sac/Dockerfile (`ln -s ./app/dockerfile ./Dockerfile`).

# TODO: build and push a Docker image to the GitLab package registry.

"docker-push-hash:peak-content-sac":
  extends: .docker-push-hash
  dependencies: 
    - download-secrets:peak-content-sac
  only:
    variables:
      - '$CI_COMMIT_BRANCH == "master" && ($CI_COMMIT_MESSAGE =~ /peak-content-sac/ || $SUBFOLDER == "peak-content-sac")'
  variables:
    CI_COMMIT_SHORT_SHA: "${CI_COMMIT_SHORT_SHA}_peak-content-sac"
    IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}"
  before_script:
    - cd ./peak-content-sac/
    - sleep 5
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

"deploy-rundeck:peak-content-sac":
  extends: .deploy-rundeck
  dependencies:
    - docker-push-hash:peak-content-sac
  when: manual
  only:
    variables:
      - '$CI_COMMIT_BRANCH == "master" && ($CI_COMMIT_MESSAGE =~ /peak-content-sac/ || $SUBFOLDER == "peak-content-sac")'
  variables:
    IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}_peak-content-sac"
    RUNDECK_MANIFEST: "deploy/rundeck.yaml"
    RUNDECK_PROJECT: "data_jobs"
  before_script:
    - apk add --no-cache curl gettext
    - cd ./peak-content-sac/