- defaultTab: nodes
  description: |-
        Applicant = Insights Team
        Summary = Content new approved Ads by region metrics pipeline
        Description = This metric aims to measure our growth in the market share associated 
                      with the auto vertical in regions. This pipeline get daily information 
                      regarding new approved notices
        Source = DW: ods.ad, ods.seller_pro_details, ods.platform, ods.region, stg.big_sellers_detail
        Destination = DW: dm_peak.content_w_region
        Aggregations = Vetical, Platform, Region
  executionEnabled: true
  group: GLOBAL-METRIC
  loglevel: DEBUG
  name: Peak - Content-NAA-Region-Metrics
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notification:
    onfailure:
      email:
        recipients: gp_data_analytics@yapo.cl
        subject: ${job.execid} ${execution.status} ${job.name} - Fallo definitivo
    onretryablefailure:
      email:
        recipients: gp_data_analytics@yapo.cl
        subject: ${job.execid} ${execution.status} ${job.name} - Fallo por reintento
  notifyAvgDurationThreshold: null
  scheduleEnabled: true
  schedule:
    month: '*'
    time:
      hour: '09'
      minute: '0'
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  retry:
    retry: 3
    delay: 20m
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/peak-content-naa-region-metrics:latest
        sudo docker run -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_DW_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/peak-content-naa-region-metrics:latest
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
