version: '3'

services:
  app:
    image: ${DOCKER_IMAGE_COMPOSE}
    container_name: ${DOCKER_CONTAINER_NAME}
    expose:
      - "5000"
    environment:
      APP_DW_SECRET: /app/db-secret
      APP_BLOCKET_SECRET: /app/blocket-secret
    volumes:
      - ~/Projects/secrets/blocket-secret:/app/blocket-secret
      - ~/Projects/secrets/db-secret-dev:/app/db-secret
