- defaultTab: nodes
  description: |-
        Daily this pipeline makes available into DWH the data related to sellers 
        of ours ads whatever its classification private or professional as well as 
        a detail available related to sellers pro to know in which categories a seller 
        is professional
  executionEnabled: true
  group: CORE
  loglevel: DEBUG
  name: Core - Ad-sellers
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notifyAvgDurationThreshold: null
  scheduleEnabled: false
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/core-ad-sellers:feat_core-ad-sellers
        sudo docker run --rm --net=host \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -v /home/bnbiuser/secrets/blocket_db:/app/blocket-secret \
                        -v /home/bnbiuser/secrets/smtp:/app/smtp-secret \
                        -e APP_DB_SECRET=/app/blocket-secret \
                        -e APP_DW_SECRET=/app/db-secret \
                        -e APP_SMTP_SECRET=/app/smtp-secret \
                        containers.mpi-internal.com/yapo/core-ad-sellers:feat_core-ad-sellers \
                        -email_from="noreply@yapo.cl" \
                        -email_to="data_team@adevinta.com"
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
