- defaultTab: nodes
  description: |-
        <Add a description about what this ETL does>
        sudo docker run -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -v /home/bnbiuser/secrets/blocket_db:/app/blocket-secret \
                        -e APP_DB_SECRET=/app/blocket-secret \
                        -e APP_DW_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/core-ads-created-daily:latest
  executionEnabled: true
  group: CORE
  loglevel: DEBUG
  name: Core - Ads-created-daily
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notification:
    onfailure:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name} - Fallo definitivo
    onretryablefailure:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name} - Fallo por reintento
  notifyAvgDurationThreshold: null
  scheduleEnabled: true
  schedule:
    month: '*'
    time:
      hour: '00'
      minute: '10'
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  retry:
    retry: 3
    delay: 20m
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/core-ads-created-daily:latest
        sudo docker run -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -v /home/bnbiuser/secrets/blocket_db:/app/blocket-secret \
                        -e APP_DB_SECRET=/app/blocket-secret \
                        -e APP_DW_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/core-ads-created-daily:latest
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
