# One .gitlab-ci.yml file for each project must be present.
# In order to run the docker-pipeline-template, a Dockerfile symlink must be placed
# into data-content/peak-revenues-advertising/Dockerfile (`ln -s ./app/dockerfile ./Dockerfile`).

"docker-push-hash:peak-revenues-advertising":
  extends: .docker-push-hash
  only:
    variables:
      - '$CI_COMMIT_BRANCH == "master" && ($CI_COMMIT_MESSAGE =~ /peak-revenues-advertising/ || $SUBFOLDER == "peak-revenues-advertising")'
  variables:
    CI_COMMIT_SHORT_SHA: "${CI_COMMIT_SHORT_SHA}_peak-revenues-advertising"
    IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}"
  before_script:
    - cd ./peak-revenues-advertising/
    - sleep 5
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

"deploy-rundeck:peak-revenues-advertising":
  extends: .deploy-rundeck
  dependencies:
    - docker-push-hash:peak-revenues-advertising
  when: manual
  only:
    variables:
      - '$CI_COMMIT_BRANCH == "master" && ($CI_COMMIT_MESSAGE =~ /peak-revenues-advertising/ || $SUBFOLDER == "peak-revenues-advertising")'
  variables:
    IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}_peak-revenues-advertising"
    RUNDECK_MANIFEST: "deploy/rundeck.yaml"
    RUNDECK_PROJECT: "data_jobs"
  before_script:
    - apk add --no-cache curl gettext
    - cd ./peak-revenues-advertising/
