version: '3'
 
services:
  app:
    image: ${DOCKER_IMAGE_COMPOSE}
    container_name: ${DOCKER_CONTAINER_NAME}
    expose:
      - "5000"
    environment:
      APP_GOOGLE_SECRET: /app/google-secret
      APP_DB_SECRET: /app/db-secret
    volumes:
      - /keys/bnbiuser:/app/db-secret
      - /keys/google_auth:/app/google-secret
